[package]
name = "da-light-integration"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Workspace integration tests for the sampling node"
rust-version.workspace = true

[dependencies]
da-adapter-mock.workspace = true
da-light-core.workspace = true
da-light-node.workspace = true
tokio.workspace = true
